# Disable sudo to speed up the build
sudo: true

# Set the build language to Python
language: python

# Set the python version to 2.7
python: 2.7

# Install the codecov pip dependency
install: 
  # - pip install codecov
  - pip install fake_rpi
  - pip install git+https://github.com/sn4k3/FakeRPi
  - pip install RPi.GPIO
  - pip install --ignore-installed six

# Run the unit test
script:
  - python main.py
  # - coverage run tests.py

# Push the results back to codecov
after_success:
  # - codecov
  - bash ./telegrambot.sh

  